DATA:
  +data_root: C:/Users/hp/Documents/code/Py/actual/Ai/inter_boot_2024/semseg/dataset/interboot                  
  +train_list: C:/Users/hp/Documents/code/Py/actual/Ai/inter_boot_2024/semseg/dataset/interboot/list/training.txt
  +val_list: C:/Users/hp/Documents/code/Py/actual/Ai/inter_boot_2024/semseg/dataset/interboot/list/validation.txt
  +classes: 40

TRAIN:
  arch: psp
  layers: 50
  sync_bn: True  # adopt sync_bn or not
  +train_h: 1080
  +train_w: 1920
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -10  # minimum random rotate
  rotate_max: 10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 255
  aux_weight: 0.4
  -train_gpu: [0, 1, 2, 3, 4, 5, 6, 7]
  workers: 16  # data loader workers
  batch_size: 16  # batch size for training
  batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.01
  epochs: 100
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed:
  print_freq: 10
  save_freq: 1
  -save_path: C:/Users/hp/Documents/code/Py/actual/Ai/inter_boot_2024/semseg/exp/interboot/pspnet50/model
  -weight:  # path to initial weight (default: none) C:\Users\hp\Documents\code\Py\ACTUAL SHIET\Ai\inter boot 2024\semseg\initmodel\resnet50_v2.pth
  resume:  # path to latest checkpoint (default: none)
  -evaluate: False  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  -test_list: C:/Users/hp/Documents/code/Py/actual/Ai/inter_boot_2024/semseg/dataset/interboot/list/validation.txt
  -split: val  # split in [train, val and test]
  base_size: 512  # based size for scaling
  +test_h: 1080
  +test_w: 1920
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [0]
  +model_path: C:/Users/hp/Documents/code/Py/actual/Ai/inter_boot_2024/semseg/exp/interboot/pspnet50/model/train_epoch_100.pth  # evaluation model path
  +save_folder: C:/Users/hp/Documents/code/Py/actual/Ai/inter_boot_2024/semseg/exp/interboot/pspnet50/result/epoch_100/val/ss  # results save folder
  +colors_path: C:/Users/hp/Documents/code/Py/actual/Ai/inter_boot_2024/semseg/data/interboot/interboot_colors.txt  # path of dataset colors
  +names_path: C:/Users/hp/Documents/code/Py/actual/Ai/inter_boot_2024/semseg/data/interboot/interboot_names.txt  # path of dataset category names
